# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - libblas-dev
      - liblapack-dev
      - libdevil-dev

matrix:
  include:
    - env: GHC_VERSION=7.10.3  STACK_YAML=stack-6.35.yaml IMAGO_DIR=imago
      addons:
        apt:
          packages:
            - libgmp-dev
            - libblas-dev
            - liblapack-dev
            - libdevil-dev
    #- env: GHC_VERSION=8.0.1   STACK_YAML=stack-7.24.yaml
    - env: GHC_VERSION=8.0.2   STACK_YAML=stack-9.1.yaml IMAGO_DIR=imago-wx-gui
      addons:
        apt:
          packages:
            - libgmp-dev
            - libblas-dev
            - liblapack-dev
            - libdevil-dev
            - libopencv-dev
            - libwxgtk3.0-dev
            - libwxgtk-media3.0-dev
    #- env: GHC_VERSION=8.2.1   STACK_YAML=stack.yaml

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

#install:
# Build dependencies
#- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- cd $IMAGO_DIR
- stack --no-terminal --install-ghc build
